name: detect changed packages

on:
    pull_request:
        branches: ['**']
        types: [opened, reopened, labeled, unlabeled, synchronize]

concurrency:
    group: detect-${{ github.event.pull_request.number }}
    cancel-in-progress: true

jobs:
    detect:
        runs-on: ubuntu-latest
        env:
            GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.ACTION_TOKEN }}
                  fetch-depth: 0
            - name: Enable corepack
              run: corepack enable
            - name: Setup pnpm and install dependencies
              uses: ./tooling/github/setup
            - name: 'detect changed packages'
              uses: NaverPayDev/changeset-actions/detect-add@main
              with:
                  github_token: ${{ secrets.ACTION_TOKEN }}
                  packages_dir: packages,share
                  skip_label: skip-detect-change
                  skip_branches: main
                  formatting_script: pnpm run markdownlint:fix
