name: "size-limit"
on:
    pull_request:
        branches: main

permissions:
    pull-requests: write

jobs:
    size:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: andresz1/size-limit-action@v1
              with:
                  build_script: "build"
                  clean_script: "clean"
                  github_token: ${{ secrets.GITHUB_TOKEN }}
